services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: auth_frontend_dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
    volumes:
      - ./logs:/app/logs